//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.DataAccessEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Orkidea.RinconCajica.Entities;
    
    public partial class RinconEntities : DbContext
    {
        public RinconEntities()
            : base("name=RinconEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountSummary> AccountSummary { get; set; }
        public virtual DbSet<ClubPartner> ClubPartner { get; set; }
        public virtual DbSet<DocumentType> DocumentType { get; set; }
        public virtual DbSet<FileType> FileType { get; set; }
        public virtual DbSet<FileUpload> FileUpload { get; set; }
        public virtual DbSet<FrontUser> FrontUser { get; set; }
        public virtual DbSet<HomeSlider> HomeSlider { get; set; }
        public virtual DbSet<InstitutionalEvent> InstitutionalEvent { get; set; }
        public virtual DbSet<JoinContest> JoinContest { get; set; }
        public virtual DbSet<JoinEvent> JoinEvent { get; set; }
        public virtual DbSet<MessageActor> MessageActor { get; set; }
        public virtual DbSet<mimetype> mimetype { get; set; }
        public virtual DbSet<NewsPaper> NewsPaper { get; set; }
        public virtual DbSet<Page> Page { get; set; }
        public virtual DbSet<PartnerConsumption> PartnerConsumption { get; set; }
        public virtual DbSet<Process> Process { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<ProjectDocument> ProjectDocument { get; set; }
        public virtual DbSet<SideBar> SideBar { get; set; }
        public virtual DbSet<Sport> Sport { get; set; }
        public virtual DbSet<SportBranch> SportBranch { get; set; }
        public virtual DbSet<SportModality> SportModality { get; set; }
        public virtual DbSet<SportSchedule> SportSchedule { get; set; }
        public virtual DbSet<ProcessDocument> ProcessDocument { get; set; }
        public virtual DbSet<MessageBitacore> MessageBitacore { get; set; }
        public virtual DbSet<CorrespondenceIn> CorrespondenceIn { get; set; }
        public virtual DbSet<Messenger> Messenger { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<Dependence> Dependence { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<CorrespondenceOut> CorrespondenceOut { get; set; }
        public virtual DbSet<Messaging> Messaging { get; set; }
    }
}
