//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.DataAccessEF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Orkidea.RinconCajica.Entities;
    
    public partial class RinconEntities : DbContext
    {
        public RinconEntities()
            : base("name=RinconEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<FileUpload> FileUpload { get; set; }
        public DbSet<HomeSlider> HomeSlider { get; set; }
        public DbSet<Page> Page { get; set; }
    }
}
