//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountSummary
    {
        public int id { get; set; }
        public string accion { get; set; }
        public int ano { get; set; }
        public int mes { get; set; }
        public string archivo { get; set; }
    }
}
