//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubPartner
    {
        public int docid { get; set; }
        public string doccl { get; set; }
        public string docto { get; set; }
        public string carnet { get; set; }
        public string accion { get; set; }
        public string cod_clie { get; set; }
        public string rel_tit { get; set; }
        public string fec_in { get; set; }
        public string nombre { get; set; }
        public string direcc { get; set; }
        public string telefn { get; set; }
        public string fax { get; set; }
        public string correo { get; set; }
        public string ciudad { get; set; }
        public string fec_nac { get; set; }
        public string estado { get; set; }
        public string doreco { get; set; }
        public string sexo { get; set; }
        public string aprob { get; set; }
        public string teleco { get; set; }
        public string fecmatr { get; set; }
        public string faxres { get; set; }
        public string faxofi { get; set; }
        public string mailofi { get; set; }
        public string mailres { get; set; }
        public string ciudadr { get; set; }
        public string jur_soc { get; set; }
        public string nacional { get; set; }
        public string acta { get; set; }
        public string traspaso { get; set; }
        public string reingreso { get; set; }
        public string origen { get; set; }
        public string fec_ret { get; set; }
        public string matant { get; set; }
        public string fecmat { get; set; }
        public string nomexc { get; set; }
        public string facdiv { get; set; }
        public string fecdiv { get; set; }
        public string nhijos { get; set; }
        public string cod_est { get; set; }
        public string docides { get; set; }
        public string docidtit { get; set; }
        public string socant { get; set; }
        public string motest { get; set; }
        public string docidpad { get; set; }
        public string usuario { get; set; }
        public string fecha { get; set; }
        public string hora { get; set; }
        public string looker { get; set; }
        public string celular { get; set; }
        public string preferido { get; set; }
        public string especial { get; set; }
        public string orden { get; set; }
        public string ciu_nac { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<System.DateTime> fechaActualizacion { get; set; }
    }
}
