//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubPartner
    {
        public int id { get; set; }
        public string doccl { get; set; }
        public string docto { get; set; }
        public string carnet { get; set; }
        public string accion { get; set; }
        public string cod_clie { get; set; }
        public string nombre { get; set; }
        public string direcc { get; set; }
        public string telefn { get; set; }
        public string fax { get; set; }
        public string correo { get; set; }
        public Nullable<System.DateTime> fec_nac { get; set; }
        public string sexo { get; set; }
        public string nhijos { get; set; }
        public string celular { get; set; }
        public Nullable<int> idUsuario { get; set; }
    }
}
