//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrespondenceOut
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int origen { get; set; }
        public int destino { get; set; }
        public string direccion { get; set; }
        public string destinatario { get; set; }
        public string tipoDocumento { get; set; }
        public string imagen { get; set; }
        public int usuarioEnvia { get; set; }
    }
}
