//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CorrespondenceIn
    {
        public int id { get; set; }
        public int remitente { get; set; }
        public int dependencia { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public int usuarioRecibe { get; set; }
        public Nullable<System.DateTime> fechaPatinado { get; set; }
    }
}
