//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentType
    {
        public DocumentType()
        {
            this.ProjectDocument = new HashSet<ProjectDocument>();
            this.ProcessDocument = new HashSet<ProcessDocument>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<ProjectDocument> ProjectDocument { get; set; }
        public virtual ICollection<ProcessDocument> ProcessDocument { get; set; }
    }
}
