//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeSlider
    {
        public System.Guid id { get; set; }
        public string urlImagen { get; set; }
        public string textoBoton1 { get; set; }
        public string urlBoton1 { get; set; }
        public string textoBoton2 { get; set; }
        public string urlBoton2 { get; set; }
        public string textoSlider { get; set; }
        public bool activo { get; set; }
    }
}
