//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeSlider
    {
        public System.Guid id { get; set; }
        public string urlImagen { get; set; }
        public string textoBoton1 { get; set; }
        public string urlBoton1 { get; set; }
        public string textoBoton2 { get; set; }
        public string urlBoton2 { get; set; }
        public string textoSlider { get; set; }
        public bool activo { get; set; }
    }
}
