//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitutionalEvent
    {
        public int id { get; set; }
        public System.DateTime inicio { get; set; }
        public Nullable<System.DateTime> fin { get; set; }
        public string nombreEvento { get; set; }
        public string etiqueta1 { get; set; }
        public string etiqueta2 { get; set; }
        public string etiqueta3 { get; set; }
        public bool visible { get; set; }
        public string poster { get; set; }
        public string urlPagina { get; set; }
    }
}
