//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstitutionalEvent
    {
        public int id { get; set; }
        public System.DateTime inicio { get; set; }
        public Nullable<System.DateTime> fin { get; set; }
        public string nombreEvento { get; set; }
        public string etiqueta1 { get; set; }
        public string etiqueta2 { get; set; }
        public string etiqueta3 { get; set; }
        public bool visible { get; set; }
        public string poster { get; set; }
        public string urlPagina { get; set; }
    }
}
