//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class JoinEvent
    {
        public int id { get; set; }
        public int idEvento { get; set; }
        public Nullable<int> idSocio { get; set; }
        public string tipoIdentificacion { get; set; }
        public string identificacion { get; set; }
        public string nombre { get; set; }
        public string telefonoFijo { get; set; }
        public string telefonoCelular { get; set; }
        public string email { get; set; }
        public string campoLibre1 { get; set; }
        public string campoLibre2 { get; set; }
        public string campoLibre3 { get; set; }
        public System.DateTime fechaInscripcion { get; set; }
    }
}
