//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messaging
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int origen { get; set; }
        public Nullable<int> usuarioEnvia { get; set; }
        public Nullable<int> dependenciaDestino { get; set; }
        public string destinatario { get; set; }
        public string descripcion { get; set; }
        public string prioridad { get; set; }
        public string direccion { get; set; }
        public System.DateTime fechaLimite { get; set; }
        public Nullable<System.DateTime> fechaRealizado { get; set; }
        public Nullable<int> idSalidaCorrespondencia { get; set; }
        public Nullable<int> mensajero { get; set; }
    }
}
