//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageActor
    {
        public MessageActor()
        {
            this.MessageBitacore = new HashSet<MessageBitacore>();
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
        public string nit { get; set; }
    
        public virtual ICollection<MessageBitacore> MessageBitacore { get; set; }
    }
}
