//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageBitacore
    {
        public string tipoRegistro { get; set; }
        public long idRegistro { get; set; }
        public System.DateTime fecha { get; set; }
        public int origen { get; set; }
        public int destino { get; set; }
        public bool entregaPersonal { get; set; }
        public byte prioridad { get; set; }
        public string descripcionCorta { get; set; }
        public string descripcionLarga { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fechaLimite { get; set; }
        public bool enviado { get; set; }
        public Nullable<int> documentoRelacionado { get; set; }
        public string imagenDocumento { get; set; }
    
        public virtual MessageActor MessageActor { get; set; }
    }
}
