//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageBitacore
    {
        public string tipoRegistro { get; set; }
        public long idRegistro { get; set; }
        public System.DateTime fecha { get; set; }
        public int origen { get; set; }
        public int destino { get; set; }
        public bool entregaPersonal { get; set; }
        public byte prioridad { get; set; }
        public string descripcionCorta { get; set; }
        public string descripcionLarga { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fechaLimite { get; set; }
        public bool enviado { get; set; }
    
        public virtual MessageActor MessageActor { get; set; }
    }
}
