//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageActor
    {
        public MessageActor()
        {
            this.MessageBitacore = new HashSet<MessageBitacore>();
        }
    
        public int id { get; set; }
        public string tipo { get; set; }
        public string descripcion { get; set; }
        public string nit { get; set; }
    
        public virtual ICollection<MessageBitacore> MessageBitacore { get; set; }
    }
}
