//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public string id { get; set; }
        public string titulo { get; set; }
        public string contenidoPublico { get; set; }
        public string contenidoPrivado { get; set; }
        public Nullable<int> idSideBar { get; set; }
    
        public virtual SideBar SideBar { get; set; }
    }
}
