//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerConsumption
    {
        public int id { get; set; }
        public string Punto_venta_a { get; set; }
        public string Producto { get; set; }
        public string Punto_venta_b { get; set; }
        public string Codigo_producto { get; set; }
        public string Cantidad { get; set; }
        public decimal Valor_producto { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Docid_consumidor { get; set; }
        public string Nufactura { get; set; }
        public string Sufijo { get; set; }
        public decimal Propina { get; set; }
        public decimal Total_fac { get; set; }
        public string Consumidor { get; set; }
        public string Docid_pagador { get; set; }
        public string Pagador { get; set; }
    }
}
