//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDocument
    {
        public int id { get; set; }
        public int idProyecto { get; set; }
        public int idTipoDocumento { get; set; }
        public string nombre { get; set; }
        public string ruta { get; set; }
    
        public virtual DocumentType DocumentType { get; set; }
        public virtual Project Project { get; set; }
    }
}
