//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SideBar
    {
        public SideBar()
        {
            this.Page = new HashSet<Page>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string contenidoPublico { get; set; }
        public string contenidoPrivado { get; set; }
    
        public virtual ICollection<Page> Page { get; set; }
    }
}
