//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport
    {
        public Sport()
        {
            this.SportBranch = new HashSet<SportBranch>();
            this.SportModality = new HashSet<SportModality>();
            this.SportSchedule = new HashSet<SportSchedule>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<SportBranch> SportBranch { get; set; }
        public virtual ICollection<SportModality> SportModality { get; set; }
        public virtual ICollection<SportSchedule> SportSchedule { get; set; }
    }
}
