//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportModality
    {
        public SportModality()
        {
            this.SportSchedule = new HashSet<SportSchedule>();
        }
    
        public int id { get; set; }
        public int idDeporte { get; set; }
        public string nombre { get; set; }
    
        public virtual Sport Sport { get; set; }
        public virtual ICollection<SportSchedule> SportSchedule { get; set; }
    }
}
