//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportBranch
    {
        public SportBranch()
        {
            this.SportSchedule = new HashSet<SportSchedule>();
        }
    
        public int id { get; set; }
        public int idDeporte { get; set; }
        public string nombre { get; set; }
    
        public virtual Sport Sport { get; set; }
        public virtual ICollection<SportSchedule> SportSchedule { get; set; }
    }
}
