//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sport
    {
        public Sport()
        {
            this.SportBranch = new HashSet<SportBranch>();
            this.SportModality = new HashSet<SportModality>();
            this.SportSchedule = new HashSet<SportSchedule>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<SportBranch> SportBranch { get; set; }
        public virtual ICollection<SportModality> SportModality { get; set; }
        public virtual ICollection<SportSchedule> SportSchedule { get; set; }
    }
}
