//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orkidea.RinconCajica.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SportSchedule
    {
        public SportSchedule()
        {
            this.JoinContest = new HashSet<JoinContest>();
        }
    
        public int id { get; set; }
        public int idDeporte { get; set; }
        public System.DateTime inicio { get; set; }
        public Nullable<System.DateTime> fin { get; set; }
        public string competencia { get; set; }
        public string categoria { get; set; }
        public Nullable<int> idModalidad { get; set; }
        public Nullable<int> idRama { get; set; }
        public bool aireacion { get; set; }
        public bool visible { get; set; }
        public string poster { get; set; }
        public bool privado { get; set; }
        public string urlPagina { get; set; }
    
        public virtual ICollection<JoinContest> JoinContest { get; set; }
        public virtual Sport Sport { get; set; }
        public virtual SportBranch SportBranch { get; set; }
        public virtual SportModality SportModality { get; set; }
    }
}
